version: "3.8"

services: 
  postgres:
    image: library/postgres:latest
    container_name: db
    restart: always
    environment: 
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
      - TZ=Australia/Melbourne
    ports: 
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/schema.sql
      # copy the sql script to insert demo values
      - ./sql/values.sql:/docker-entrypoint-initdb.d/values.sql
      # local host timezone & localtime info update
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    
  jupyterlab:

    build: .
    container_name: jupyterlab
    ports:
     - 8888:8888
    volumes:
      - ./code:/home/jovyan/work
      # local host timezone & localtime info update
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
    - JUPYTER_TOKEN=easy
  
volumes:
  postgres:
  code:
