@startuml
!pragma layout smetana

scale 2
title lfric

class psql.py{
    +get_engine_from_settings()
    +get_engine(user, passwd, host, port, db)
    +get_database()
    +get_session()
    +db
    +session
    +Base
}

class sever_setting {
    +postgresql

}

class orm_chema {
    +model_config()
    +model_run()
    +model_profile()
    +Base.metadata.create_all(db)
}

class orm_upload {
    
}

@enduml