version: "3.8"

services: 
  postgres:
    image: docker.io/library/postgres:latest
    container_name: lfric-test-db
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports: 
      - 54320:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./db/shema.sql:/docker-entrypoint-initdb.d/shema.sql
      # copy the sql script to insert values
      # - ./db/values.sql:/docker-entrypoint-initdb.d/values.sql
    
  jupyterlab:
    build: .
    command: start-notebook.sh
    ports:
     - 8888:8888
    volumes:
      - ./code:/home/jovyan/work
  
volumes:
  postgres:
  code: